server:
  port: 8082

spring:  datasource:    url: jdbc:h2:mem:testDB
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    platform: org.hibernate.dialect.H2Dialect  
  h2:    console:      path: /h2Console
      enabled: true
        jpa:    show-sql: true
    hibernate:      ddl-auto: update